### ISSUE TITLE
err dynamic address for lsp

### ISSUE THREAD

**Issue by qsyqian** [alauda/kube-ovn#183]
Create deployment with follow yaml file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-ovn
  name: static-deployment
  labels:
    app: static-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-deployment
  template:
    metadata:
      labels:
        app: static-deployment
      annotations:
        ovn.kubernetes.io/ip_pool: "172.50.1.5"
    spec:
      containers:
      - name: static-deployment
        image: centos
        command:
        - sleep
        - "3600"
```
and get following pod:
```
# kubectl get po -n kube-ovn -o wide | grep static
static-deployment-56ff4bdd56-lmpm2     1/1     Running   0          19s     172.50.1.5    10.18.124.1   <none>           <none>
```
then check the lsp info:
```
# kubectl ko nbctl list logical-switch_port static-deployment-56ff4bdd56-lmpm2.kube-ovn
_uuid               : 386fa1f7-a203-48f5-a709-e07cf4b078f8
addresses           : ["dynamic 172.50.1.5"]
dhcpv4_options      : []
dhcpv6_options      : []
dynamic_addresses   : "0a:00:00:32:01:06 172.50.1.8"
enabled             : []
external_ids        : {}
name                : "static-deployment-56ff4bdd56-lmpm2.kube-ovn"
options             : {}
parent_name         : []
port_security       : ["0a:00:00:32:01:06 172.50.1.5/24"]
tag                 : []
tag_request         : []
type                : ""
up                  : true
```
the addresses and dynamic_addresses have different ip address.
