### ISSUE TITLE
Error when creating subnet

### ISSUE THREAD

**Issue by rootdeep** [alauda/kube-ovn#243]
when I create a subnet with cni kube-ovn , an error accurs. the error log from terminal as follow:

Error from server (MethodNotAllowed): error when creating "subnet-ns5.yaml": the server does not allow this method on the requested resource (post subnets.kubeovn.io)

Bellow is the content of subnet-ns5.yaml

```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet-ns5
spec:
  protocol: IPv4
  cidrBlock: 10.81.0.0/16
  excludeIps:
  - 10.81.0.1..10.81.0.10
  gateway: 10.81.0.1
  namespaces:
  - ns5
```
