### ISSUE TITLE
lb does not delete when svc deleted

### ISSUE THREAD

**Issue by qsyqian** [alauda/kube-ovn#254]
when create a service like this:
```
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
  type: ClusterIP
```
and get this:
```
# kubectl get svc tomcat -o wide
NAME     TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE     SELECTOR
tomcat   ClusterIP   10.68.64.16   <none>        80/TCP    6m13s   app=tomcat
# kubectl get ep tomcat -o wide
NAME     ENDPOINTS         AGE
tomcat   172.20.1.2:8080   6m28s
```

then delete svc tomcat and recreate it for several times, and get lb like this:
```
kubectl ko nbctl lb-list | grep 172.20.1.2:8080
                                                            tcp        10.68.23.164:80        172.20.1.2:8080
                                                            tcp        10.68.31.230:8080      172.20.1.2:8080
                                                            tcp        10.68.64.16:80         172.20.1.2:8080
                                                            tcp        10.68.97.140:80        172.20.1.2:8080
```
