### ISSUE TITLE
failed to resolve dns kubernetes.default, lookup kubernetes.default on 10.96.0.10:53: dial udp 10.96.0.10:53: i/o timeout

### ISSUE THREAD

**Issue by gitnote-images** [alauda/kube-ovn#261]
System：centos7.7 and centos7.6
Kernel：5.5.7-1.el7.elrepo.x86_64 and 3.10.0-1062.12.1.el7.x86_64
Docker：19.03.6
kubernetes：1.17.3
kube-ovn：1.0.0

# setup k8s master by kubeadm
$ kubeadm init --config=kubeadm-config.yaml
configfile，such as：
```
piVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.122.8
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: k8s-master01
  taints:
  - effect: PreferNoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: v1.17.3
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
featureGates:
  SupportIPVSProxyMode: true
mode: ipvs
```

# run nginx pod
$ kubectl run nginx --image=nginx

# operate ping
$ kubectl exec -it nginx-6db489d4b7-x898l bash
ping www.baidu.com is ok

# edit kubelet config

$ vi /etc/sysconfig/kubelet
KUBELET_EXTRA_ARGS="--fail-swap-on=false --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice --eviction-hard=memory.available<5%,nodefs.available<10%,nodefs.inodesFree<10% --node-status-update-frequency=10s --eviction-pressure-transition-period=30s --enforce-node-allocatable=pods,kube-reserved --cgroup-driver=cgroupfs --kube-reserved=cpu=1,memory=2Gi,ephemeral-storage=10Gi --kube-reserved-cgroup=/system.slice/kubelet.service --max-open-files=10000"

$ vi /usr/lib/systemd/system/kubelet.service
[Service]
ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/cpuset/system.slice/kubelet.service#新增
ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/hugetlb/system.slice/kubelet.service#新增

# restart kubelet
$ systemctl daemon-reload && systemctl restart kubelet

# operate ping
$ kubectl exec -it nginx-6db489d4b7-x898l bash
ping www.baidu.com is not ok

# kube-ovn-pinger log
I0307 04:15:25.118370   13026 ping.go:167] start to check apiserver connectivity
I0307 04:15:25.119306   13026 ping.go:176] connect to apiserver success in 0.93ms
I0307 04:15:25.119326   13026 ping.go:40] start to check node connectivity
I0307 04:15:25.922280   13026 ping.go:62] ping node: k8s-master01 192.168.122.201, count: 3, loss count 0, average rtt 1.97ms
I0307 04:15:25.922309   13026 ping.go:78] start to check pod connectivity
I0307 04:15:26.530532   13026 ping.go:105] ping pod: kube-ovn-pinger-z24rt 10.16.0.4, count: 3, loss count 0, average rtt 0.34ms
I0307 04:15:26.530612   13026 ping.go:150] start to check dns connectivity
E0307 04:15:36.532114   13026 ping.go:158] failed to resolve dns kubernetes.default, lookup kubernetes.default on 10.96.0.10:53: dial udp 10.96.0.10:53: i/o timeout
I0307 04:15:36.532183   13026 ping.go:125] start to check ping external to 114.114.114.114
I0307 04:15:37.244788   13026 ping.go:138] ping external address: 114.114.114.114, total count: 3, loss count 0, average rtt 86.73ms

# this operate use weave is work
