### ISSUE TITLE
dpdk can not use 100% cpu

### ISSUE THREAD

**Issue by junka** [alauda/kube-ovn#528]
Hi there,  
I can see cpu limitations in the file ovn-dpdk.yaml  for the ovs-dpdk container like below:
```
resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1000m
              memory: 2Gi
```
This will cause that dpdk pmd thread run in 25% cpu. Is that on purpose? This could harm the performance.
